pygments: false
paginate: 5

encoding: utf-8

title: shhp的博客·学无止境

author:
 name: shhp
 email: herculeshhp@gmail.com

copyright:
 - Design by <a href="http://ipsleung.com">Iris Leung</a>

css:
 - /lib/blog.css
 - /lib/syntax.css